// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package meta

import . "github.com/Hurricanezwf/rate-limiter/types"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_Meta struct {
	Value                map[string]*PB_M `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PB_Meta) Reset()         { *m = PB_Meta{} }
func (m *PB_Meta) String() string { return proto.CompactTextString(m) }
func (*PB_Meta) ProtoMessage()    {}
func (*PB_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_0c4260c0da947ee5, []int{0}
}
func (m *PB_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_Meta.Unmarshal(m, b)
}
func (m *PB_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_Meta.Marshal(b, m, deterministic)
}
func (dst *PB_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_Meta.Merge(dst, src)
}
func (m *PB_Meta) XXX_Size() int {
	return xxx_messageInfo_PB_Meta.Size(m)
}
func (m *PB_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_PB_Meta proto.InternalMessageInfo

func (m *PB_Meta) GetValue() map[string]*PB_M {
	if m != nil {
		return m.Value
	}
	return nil
}

type PB_M struct {
	RcTypeId             *PB_Bytes  `protobuf:"bytes,1,opt,name=rcTypeId,proto3" json:"rcTypeId,omitempty"`
	Quota                *PB_Uint32 `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	CanBorrow            *PB_Queue  `protobuf:"bytes,3,opt,name=canBorrow,proto3" json:"canBorrow,omitempty"`
	Recycled             *PB_Queue  `protobuf:"bytes,4,opt,name=recycled,proto3" json:"recycled,omitempty"`
	Used                 *PB_Map    `protobuf:"bytes,5,opt,name=used,proto3" json:"used,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PB_M) Reset()         { *m = PB_M{} }
func (m *PB_M) String() string { return proto.CompactTextString(m) }
func (*PB_M) ProtoMessage()    {}
func (*PB_M) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_0c4260c0da947ee5, []int{1}
}
func (m *PB_M) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_M.Unmarshal(m, b)
}
func (m *PB_M) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_M.Marshal(b, m, deterministic)
}
func (dst *PB_M) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_M.Merge(dst, src)
}
func (m *PB_M) XXX_Size() int {
	return xxx_messageInfo_PB_M.Size(m)
}
func (m *PB_M) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_M.DiscardUnknown(m)
}

var xxx_messageInfo_PB_M proto.InternalMessageInfo

func (m *PB_M) GetRcTypeId() *PB_Bytes {
	if m != nil {
		return m.RcTypeId
	}
	return nil
}

func (m *PB_M) GetQuota() *PB_Uint32 {
	if m != nil {
		return m.Quota
	}
	return nil
}

func (m *PB_M) GetCanBorrow() *PB_Queue {
	if m != nil {
		return m.CanBorrow
	}
	return nil
}

func (m *PB_M) GetRecycled() *PB_Queue {
	if m != nil {
		return m.Recycled
	}
	return nil
}

func (m *PB_M) GetUsed() *PB_Map {
	if m != nil {
		return m.Used
	}
	return nil
}

type PB_BorrowRecord struct {
	ClientID             *PB_Bytes  `protobuf:"bytes,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	RcID                 *PB_String `protobuf:"bytes,2,opt,name=rcID,proto3" json:"rcID,omitempty"`
	BorrowAt             *PB_Int64  `protobuf:"bytes,3,opt,name=borrowAt,proto3" json:"borrowAt,omitempty"`
	ExpireAt             *PB_Int64  `protobuf:"bytes,4,opt,name=expireAt,proto3" json:"expireAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PB_BorrowRecord) Reset()         { *m = PB_BorrowRecord{} }
func (m *PB_BorrowRecord) String() string { return proto.CompactTextString(m) }
func (*PB_BorrowRecord) ProtoMessage()    {}
func (*PB_BorrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_0c4260c0da947ee5, []int{2}
}
func (m *PB_BorrowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_BorrowRecord.Unmarshal(m, b)
}
func (m *PB_BorrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_BorrowRecord.Marshal(b, m, deterministic)
}
func (dst *PB_BorrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_BorrowRecord.Merge(dst, src)
}
func (m *PB_BorrowRecord) XXX_Size() int {
	return xxx_messageInfo_PB_BorrowRecord.Size(m)
}
func (m *PB_BorrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_BorrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PB_BorrowRecord proto.InternalMessageInfo

func (m *PB_BorrowRecord) GetClientID() *PB_Bytes {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *PB_BorrowRecord) GetRcID() *PB_String {
	if m != nil {
		return m.RcID
	}
	return nil
}

func (m *PB_BorrowRecord) GetBorrowAt() *PB_Int64 {
	if m != nil {
		return m.BorrowAt
	}
	return nil
}

func (m *PB_BorrowRecord) GetExpireAt() *PB_Int64 {
	if m != nil {
		return m.ExpireAt
	}
	return nil
}

func init() {
	proto.RegisterType((*PB_Meta)(nil), "meta.PB_Meta")
	proto.RegisterMapType((map[string]*PB_M)(nil), "meta.PB_Meta.ValueEntry")
	proto.RegisterType((*PB_M)(nil), "meta.PB_M")
	proto.RegisterType((*PB_BorrowRecord)(nil), "meta.PB_BorrowRecord")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_meta_0c4260c0da947ee5) }

var fileDescriptor_meta_0c4260c0da947ee5 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xd9, 0x36, 0x79, 0x5f, 0x3b, 0x41, 0x5a, 0xf6, 0x14, 0x7a, 0x8a, 0x45, 0xa4, 0x20,
	0xe6, 0x90, 0x8a, 0x88, 0xb7, 0x86, 0x7a, 0xc8, 0xa1, 0x50, 0xd7, 0x3f, 0xd7, 0x92, 0x6e, 0x06,
	0x09, 0xd6, 0x24, 0x6e, 0x27, 0x6a, 0x4e, 0x7e, 0x33, 0x3f, 0x88, 0x9f, 0x46, 0x76, 0xd3, 0x36,
	0x60, 0xf4, 0xb6, 0xcc, 0xf3, 0xcb, 0x6f, 0xe6, 0x81, 0x00, 0x3c, 0x23, 0xc5, 0x7e, 0xa1, 0x72,
	0xca, 0xb9, 0xa5, 0xdf, 0x43, 0x87, 0xaa, 0x02, 0x37, 0xf5, 0x68, 0xf4, 0x01, 0xff, 0x17, 0xe1,
	0x72, 0x8e, 0x14, 0x73, 0x1f, 0xec, 0x87, 0x78, 0x5d, 0xa2, 0xcb, 0xbc, 0xee, 0xd8, 0x09, 0x5c,
	0xdf, 0x7c, 0xb9, 0x4d, 0x7d, 0x13, 0x5d, 0x67, 0xa4, 0x2a, 0x51, 0x63, 0xc3, 0x19, 0x40, 0x33,
	0xe4, 0x03, 0xe8, 0x3e, 0x61, 0xe5, 0x32, 0x8f, 0x8d, 0x7b, 0x42, 0x3f, 0xb9, 0x07, 0xf6, 0xab,
	0xf1, 0x75, 0x3c, 0x36, 0x76, 0x02, 0x68, 0x7c, 0xa2, 0x0e, 0xae, 0x3a, 0x97, 0x6c, 0xf4, 0xc5,
	0xc0, 0xd2, 0x33, 0x7e, 0x0a, 0x07, 0x4a, 0xde, 0x55, 0x05, 0x46, 0x89, 0xb1, 0x38, 0x41, 0xdf,
	0xaf, 0x2f, 0x5d, 0x84, 0xcb, 0xb0, 0x22, 0xdc, 0x88, 0x3d, 0xc0, 0x4f, 0xc0, 0x7e, 0x29, 0x73,
	0x8a, 0xb7, 0xee, 0x41, 0x43, 0xde, 0xa7, 0x19, 0x4d, 0x02, 0x51, 0xc7, 0xfc, 0x0c, 0x7a, 0x32,
	0xce, 0xc2, 0x5c, 0xa9, 0xfc, 0xcd, 0xed, 0xfe, 0xb4, 0xde, 0x94, 0x58, 0xa2, 0x68, 0x08, 0x73,
	0x03, 0xca, 0x4a, 0xae, 0x31, 0x71, 0xad, 0xdf, 0xe9, 0x3d, 0xc0, 0x8f, 0xc0, 0x2a, 0x37, 0x98,
	0xb8, 0xb6, 0x01, 0x0f, 0x1b, 0x70, 0x1e, 0x17, 0xc2, 0x44, 0xa3, 0x4f, 0x06, 0x7d, 0x7d, 0xbd,
	0xb1, 0x0b, 0x94, 0xb9, 0x4a, 0xf4, 0x0e, 0xb9, 0x4e, 0x31, 0xa3, 0x68, 0xf6, 0x67, 0xcf, 0x1d,
	0xc0, 0x8f, 0xc1, 0x52, 0x32, 0x9a, 0xb5, 0x6b, 0xde, 0x92, 0x4a, 0xb3, 0x47, 0x61, 0x52, 0xad,
	0x5c, 0x99, 0x15, 0x53, 0x6a, 0x97, 0x8c, 0x32, 0xba, 0x38, 0x17, 0x7b, 0x40, 0xc3, 0xf8, 0x5e,
	0xa4, 0x0a, 0xa7, 0xd4, 0xee, 0xb8, 0x85, 0x77, 0xc0, 0xea, 0x9f, 0xf9, 0x4b, 0x26, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x0b, 0xfc, 0xed, 0xe6, 0x46, 0x02, 0x00, 0x00,
}
