// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_Meta struct {
	Value                map[string]*PB_Manager `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PB_Meta) Reset()         { *m = PB_Meta{} }
func (m *PB_Meta) String() string { return proto.CompactTextString(m) }
func (*PB_Meta) ProtoMessage()    {}
func (*PB_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_d8c774e544aed08c, []int{0}
}
func (m *PB_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_Meta.Unmarshal(m, b)
}
func (m *PB_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_Meta.Marshal(b, m, deterministic)
}
func (dst *PB_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_Meta.Merge(dst, src)
}
func (m *PB_Meta) XXX_Size() int {
	return xxx_messageInfo_PB_Meta.Size(m)
}
func (m *PB_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_PB_Meta proto.InternalMessageInfo

func (m *PB_Meta) GetValue() map[string]*PB_Manager {
	if m != nil {
		return m.Value
	}
	return nil
}

type PB_Manager struct {
	RCType               []byte             `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	Quota                uint32             `protobuf:"varint,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	CanBorrow            []string           `protobuf:"bytes,3,rep,name=CanBorrow,proto3" json:"CanBorrow,omitempty"`
	Recycled             []string           `protobuf:"bytes,4,rep,name=Recycled,proto3" json:"Recycled,omitempty"`
	Used                 []*PB_BorrowRecord `protobuf:"bytes,5,rep,name=Used,proto3" json:"Used,omitempty"`
	UsedCount            uint32             `protobuf:"varint,6,opt,name=UsedCount,proto3" json:"UsedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PB_Manager) Reset()         { *m = PB_Manager{} }
func (m *PB_Manager) String() string { return proto.CompactTextString(m) }
func (*PB_Manager) ProtoMessage()    {}
func (*PB_Manager) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_d8c774e544aed08c, []int{1}
}
func (m *PB_Manager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_Manager.Unmarshal(m, b)
}
func (m *PB_Manager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_Manager.Marshal(b, m, deterministic)
}
func (dst *PB_Manager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_Manager.Merge(dst, src)
}
func (m *PB_Manager) XXX_Size() int {
	return xxx_messageInfo_PB_Manager.Size(m)
}
func (m *PB_Manager) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_Manager.DiscardUnknown(m)
}

var xxx_messageInfo_PB_Manager proto.InternalMessageInfo

func (m *PB_Manager) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *PB_Manager) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *PB_Manager) GetCanBorrow() []string {
	if m != nil {
		return m.CanBorrow
	}
	return nil
}

func (m *PB_Manager) GetRecycled() []string {
	if m != nil {
		return m.Recycled
	}
	return nil
}

func (m *PB_Manager) GetUsed() []*PB_BorrowRecord {
	if m != nil {
		return m.Used
	}
	return nil
}

func (m *PB_Manager) GetUsedCount() uint32 {
	if m != nil {
		return m.UsedCount
	}
	return 0
}

type PB_BorrowRecord struct {
	ClientID             []byte   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RCID                 string   `protobuf:"bytes,2,opt,name=RCID,proto3" json:"RCID,omitempty"`
	BorrowAt             int64    `protobuf:"varint,3,opt,name=BorrowAt,proto3" json:"BorrowAt,omitempty"`
	ExpireAt             int64    `protobuf:"varint,4,opt,name=ExpireAt,proto3" json:"ExpireAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PB_BorrowRecord) Reset()         { *m = PB_BorrowRecord{} }
func (m *PB_BorrowRecord) String() string { return proto.CompactTextString(m) }
func (*PB_BorrowRecord) ProtoMessage()    {}
func (*PB_BorrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_d8c774e544aed08c, []int{2}
}
func (m *PB_BorrowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_BorrowRecord.Unmarshal(m, b)
}
func (m *PB_BorrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_BorrowRecord.Marshal(b, m, deterministic)
}
func (dst *PB_BorrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_BorrowRecord.Merge(dst, src)
}
func (m *PB_BorrowRecord) XXX_Size() int {
	return xxx_messageInfo_PB_BorrowRecord.Size(m)
}
func (m *PB_BorrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_BorrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PB_BorrowRecord proto.InternalMessageInfo

func (m *PB_BorrowRecord) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *PB_BorrowRecord) GetRCID() string {
	if m != nil {
		return m.RCID
	}
	return ""
}

func (m *PB_BorrowRecord) GetBorrowAt() int64 {
	if m != nil {
		return m.BorrowAt
	}
	return 0
}

func (m *PB_BorrowRecord) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func init() {
	proto.RegisterType((*PB_Meta)(nil), "meta.PB_Meta")
	proto.RegisterMapType((map[string]*PB_Manager)(nil), "meta.PB_Meta.ValueEntry")
	proto.RegisterType((*PB_Manager)(nil), "meta.PB_Manager")
	proto.RegisterType((*PB_BorrowRecord)(nil), "meta.PB_BorrowRecord")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_meta_d8c774e544aed08c) }

var fileDescriptor_meta_d8c774e544aed08c = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xd9, 0x26, 0xe9, 0xff, 0x9f, 0xa9, 0x62, 0x59, 0x54, 0x96, 0xe2, 0x21, 0xf4, 0x20,
	0xf1, 0x92, 0x43, 0xbd, 0x88, 0xb7, 0x36, 0xed, 0xa1, 0x82, 0xa0, 0x83, 0x7a, 0x95, 0xb5, 0x1d,
	0xa4, 0x58, 0xb3, 0x65, 0xdd, 0xaa, 0x79, 0x00, 0x1f, 0xcb, 0x77, 0x93, 0x9d, 0xad, 0x09, 0x78,
	0xca, 0x7c, 0xf3, 0xfb, 0xe6, 0x9b, 0x0c, 0x0b, 0xf0, 0x4a, 0x4e, 0x17, 0x1b, 0x6b, 0x9c, 0x91,
	0xb1, 0xaf, 0x87, 0x5f, 0x02, 0xfe, 0xdd, 0x4c, 0x1e, 0xaf, 0xc9, 0x69, 0x59, 0x40, 0xf2, 0xa0,
	0xd7, 0x5b, 0x52, 0x22, 0x8b, 0xf2, 0xde, 0x48, 0x15, 0xec, 0xde, 0xd1, 0x82, 0xd1, 0xac, 0x72,
	0xb6, 0xc6, 0x60, 0x1b, 0x5c, 0x01, 0xb4, 0x4d, 0xd9, 0x87, 0xe8, 0x85, 0x6a, 0x25, 0x32, 0x91,
	0xa7, 0xe8, 0x4b, 0x79, 0x0a, 0xc9, 0x3b, 0xe7, 0x75, 0x32, 0x91, 0xf7, 0x46, 0xfd, 0x36, 0x4f,
	0x57, 0xfa, 0x99, 0x2c, 0x06, 0x7c, 0xd9, 0xb9, 0x10, 0xc3, 0x6f, 0x01, 0xd0, 0x12, 0x79, 0x0c,
	0x5d, 0x2c, 0xef, 0xea, 0x0d, 0x71, 0xde, 0x1e, 0xee, 0x94, 0x3c, 0x84, 0xe4, 0x76, 0x6b, 0x9c,
	0xe6, 0xc8, 0x7d, 0x0c, 0x42, 0x9e, 0x40, 0x5a, 0xea, 0x6a, 0x62, 0xac, 0x35, 0x1f, 0x2a, 0xca,
	0xa2, 0x3c, 0xc5, 0xb6, 0x21, 0x07, 0xf0, 0x1f, 0x69, 0x51, 0x2f, 0xd6, 0xb4, 0x54, 0x31, 0xc3,
	0x46, 0xcb, 0x33, 0x88, 0xef, 0xdf, 0x68, 0xa9, 0x12, 0xbe, 0xf8, 0xa8, 0xf9, 0xc3, 0x30, 0x8a,
	0xb4, 0x30, 0x76, 0x89, 0x6c, 0xf1, 0x4b, 0xfc, 0xb7, 0x34, 0xdb, 0xca, 0xa9, 0x2e, 0xaf, 0x6f,
	0x1b, 0xc3, 0x1a, 0x0e, 0xfe, 0x8c, 0xf9, 0xbd, 0xe5, 0x7a, 0x45, 0x95, 0x9b, 0x4f, 0x77, 0x57,
	0x34, 0x5a, 0x4a, 0x88, 0xb1, 0x9c, 0x4f, 0xf9, 0x8c, 0x14, 0xb9, 0xf6, 0xfe, 0x30, 0x3f, 0x76,
	0x2a, 0xca, 0x44, 0x1e, 0x61, 0xa3, 0x3d, 0x9b, 0x7d, 0x6e, 0x56, 0x96, 0xc6, 0x4e, 0xc5, 0x81,
	0xfd, 0xea, 0xa7, 0x2e, 0xbf, 0xe7, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x68, 0xd4,
	0x8d, 0xdd, 0x01, 0x00, 0x00,
}
