// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meta.proto

package meta

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PB_Meta struct {
	Value                map[string]*PB_Manager `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PB_Meta) Reset()         { *m = PB_Meta{} }
func (m *PB_Meta) String() string { return proto.CompactTextString(m) }
func (*PB_Meta) ProtoMessage()    {}
func (*PB_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_af5e4040b162a749, []int{0}
}
func (m *PB_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_Meta.Unmarshal(m, b)
}
func (m *PB_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_Meta.Marshal(b, m, deterministic)
}
func (dst *PB_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_Meta.Merge(dst, src)
}
func (m *PB_Meta) XXX_Size() int {
	return xxx_messageInfo_PB_Meta.Size(m)
}
func (m *PB_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_PB_Meta proto.InternalMessageInfo

func (m *PB_Meta) GetValue() map[string]*PB_Manager {
	if m != nil {
		return m.Value
	}
	return nil
}

type PB_Manager struct {
	RCType               []byte             `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	Quota                uint32             `protobuf:"varint,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	CanBorrow            []string           `protobuf:"bytes,3,rep,name=CanBorrow,proto3" json:"CanBorrow,omitempty"`
	Recycled             []string           `protobuf:"bytes,4,rep,name=Recycled,proto3" json:"Recycled,omitempty"`
	Used                 []*PB_BorrowRecord `protobuf:"bytes,5,rep,name=Used,proto3" json:"Used,omitempty"`
	UsedCount            uint32             `protobuf:"varint,6,opt,name=UsedCount,proto3" json:"UsedCount,omitempty"`
	ResetInterval        int64              `protobuf:"varint,7,opt,name=ResetInterval,proto3" json:"ResetInterval,omitempty"`
	LastReset            int64              `protobuf:"varint,8,opt,name=LastReset,proto3" json:"LastReset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PB_Manager) Reset()         { *m = PB_Manager{} }
func (m *PB_Manager) String() string { return proto.CompactTextString(m) }
func (*PB_Manager) ProtoMessage()    {}
func (*PB_Manager) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_af5e4040b162a749, []int{1}
}
func (m *PB_Manager) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_Manager.Unmarshal(m, b)
}
func (m *PB_Manager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_Manager.Marshal(b, m, deterministic)
}
func (dst *PB_Manager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_Manager.Merge(dst, src)
}
func (m *PB_Manager) XXX_Size() int {
	return xxx_messageInfo_PB_Manager.Size(m)
}
func (m *PB_Manager) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_Manager.DiscardUnknown(m)
}

var xxx_messageInfo_PB_Manager proto.InternalMessageInfo

func (m *PB_Manager) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *PB_Manager) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *PB_Manager) GetCanBorrow() []string {
	if m != nil {
		return m.CanBorrow
	}
	return nil
}

func (m *PB_Manager) GetRecycled() []string {
	if m != nil {
		return m.Recycled
	}
	return nil
}

func (m *PB_Manager) GetUsed() []*PB_BorrowRecord {
	if m != nil {
		return m.Used
	}
	return nil
}

func (m *PB_Manager) GetUsedCount() uint32 {
	if m != nil {
		return m.UsedCount
	}
	return 0
}

func (m *PB_Manager) GetResetInterval() int64 {
	if m != nil {
		return m.ResetInterval
	}
	return 0
}

func (m *PB_Manager) GetLastReset() int64 {
	if m != nil {
		return m.LastReset
	}
	return 0
}

type PB_BorrowRecord struct {
	ClientID             []byte   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RCID                 string   `protobuf:"bytes,2,opt,name=RCID,proto3" json:"RCID,omitempty"`
	BorrowAt             int64    `protobuf:"varint,3,opt,name=BorrowAt,proto3" json:"BorrowAt,omitempty"`
	ExpireAt             int64    `protobuf:"varint,4,opt,name=ExpireAt,proto3" json:"ExpireAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PB_BorrowRecord) Reset()         { *m = PB_BorrowRecord{} }
func (m *PB_BorrowRecord) String() string { return proto.CompactTextString(m) }
func (*PB_BorrowRecord) ProtoMessage()    {}
func (*PB_BorrowRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_af5e4040b162a749, []int{2}
}
func (m *PB_BorrowRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PB_BorrowRecord.Unmarshal(m, b)
}
func (m *PB_BorrowRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PB_BorrowRecord.Marshal(b, m, deterministic)
}
func (dst *PB_BorrowRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PB_BorrowRecord.Merge(dst, src)
}
func (m *PB_BorrowRecord) XXX_Size() int {
	return xxx_messageInfo_PB_BorrowRecord.Size(m)
}
func (m *PB_BorrowRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PB_BorrowRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PB_BorrowRecord proto.InternalMessageInfo

func (m *PB_BorrowRecord) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *PB_BorrowRecord) GetRCID() string {
	if m != nil {
		return m.RCID
	}
	return ""
}

func (m *PB_BorrowRecord) GetBorrowAt() int64 {
	if m != nil {
		return m.BorrowAt
	}
	return 0
}

func (m *PB_BorrowRecord) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func init() {
	proto.RegisterType((*PB_Meta)(nil), "meta.PB_Meta")
	proto.RegisterMapType((map[string]*PB_Manager)(nil), "meta.PB_Meta.ValueEntry")
	proto.RegisterType((*PB_Manager)(nil), "meta.PB_Manager")
	proto.RegisterType((*PB_BorrowRecord)(nil), "meta.PB_BorrowRecord")
}

func init() { proto.RegisterFile("meta.proto", fileDescriptor_meta_af5e4040b162a749) }

var fileDescriptor_meta_af5e4040b162a749 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcf, 0x4b, 0xeb, 0x40,
	0x10, 0x26, 0x4d, 0xd2, 0x36, 0xd3, 0x57, 0x5e, 0x59, 0xde, 0x7b, 0x2c, 0xe5, 0x1d, 0x42, 0x11,
	0x89, 0x97, 0x1c, 0xea, 0x45, 0xbc, 0xb5, 0x69, 0x0f, 0x15, 0x05, 0x1d, 0xd4, 0xab, 0xac, 0xed,
	0x20, 0xc5, 0x98, 0x2d, 0xdb, 0x6d, 0x35, 0x47, 0x0f, 0xfe, 0xdf, 0xb2, 0x93, 0x9a, 0xa0, 0xa7,
	0xcc, 0xf7, 0x63, 0xbe, 0x99, 0x0c, 0x0b, 0xf0, 0x42, 0x56, 0xa5, 0x1b, 0xa3, 0xad, 0x16, 0x81,
	0xab, 0x47, 0x1f, 0x1e, 0x74, 0xae, 0xa7, 0x0f, 0x57, 0x64, 0x95, 0x48, 0x21, 0xbc, 0x57, 0xf9,
	0x8e, 0xa4, 0x17, 0xfb, 0x49, 0x6f, 0x2c, 0x53, 0x76, 0x1f, 0xd4, 0x94, 0xa5, 0x79, 0x61, 0x4d,
	0x89, 0x95, 0x6d, 0x78, 0x01, 0xd0, 0x90, 0x62, 0x00, 0xfe, 0x33, 0x95, 0xd2, 0x8b, 0xbd, 0x24,
	0x42, 0x57, 0x8a, 0x63, 0x08, 0xf7, 0x9c, 0xd7, 0x8a, 0xbd, 0xa4, 0x37, 0x1e, 0x34, 0x79, 0xaa,
	0x50, 0x4f, 0x64, 0xb0, 0x92, 0xcf, 0x5b, 0x67, 0xde, 0xe8, 0xbd, 0x05, 0xd0, 0x28, 0xe2, 0x1f,
	0xb4, 0x31, 0xbb, 0x2d, 0x37, 0xc4, 0x79, 0xbf, 0xf0, 0x80, 0xc4, 0x1f, 0x08, 0x6f, 0x76, 0xda,
	0x2a, 0x8e, 0xec, 0x63, 0x05, 0xc4, 0x7f, 0x88, 0x32, 0x55, 0x4c, 0xb5, 0x31, 0xfa, 0x55, 0xfa,
	0xb1, 0x9f, 0x44, 0xd8, 0x10, 0x62, 0x08, 0x5d, 0xa4, 0x65, 0xb9, 0xcc, 0x69, 0x25, 0x03, 0x16,
	0x6b, 0x2c, 0x4e, 0x20, 0xb8, 0xdb, 0xd2, 0x4a, 0x86, 0xfc, 0xc7, 0x7f, 0xeb, 0x0d, 0xab, 0x56,
	0xa4, 0xa5, 0x36, 0x2b, 0x64, 0x8b, 0x1b, 0xe2, 0xbe, 0x99, 0xde, 0x15, 0x56, 0xb6, 0x79, 0x7c,
	0x43, 0x88, 0x23, 0xe8, 0x23, 0x6d, 0xc9, 0x2e, 0x0a, 0x4b, 0x66, 0xaf, 0x72, 0xd9, 0x89, 0xbd,
	0xc4, 0xc7, 0xef, 0xa4, 0xcb, 0xb8, 0x54, 0x5b, 0xcb, 0xa4, 0xec, 0xb2, 0xa3, 0x21, 0x46, 0x25,
	0xfc, 0xfe, 0x31, 0xda, 0xed, 0x9e, 0xe5, 0x6b, 0x2a, 0xec, 0x62, 0x76, 0xb8, 0x44, 0x8d, 0x85,
	0x80, 0x00, 0xb3, 0xc5, 0x8c, 0x4f, 0x11, 0x21, 0xd7, 0xce, 0x5f, 0xf5, 0x4f, 0xac, 0xf4, 0x39,
	0xbf, 0xc6, 0x4e, 0x9b, 0xbf, 0x6d, 0xd6, 0x86, 0x26, 0x56, 0x06, 0x95, 0xf6, 0x85, 0x1f, 0xdb,
	0xfc, 0x26, 0x4e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x05, 0xec, 0x5c, 0x3f, 0x21, 0x02, 0x00,
	0x00,
}
