# 【Httpd配置】
Httpd:
  # Http监听地址，不能为0.0.0.0
  Listen: 127.0.0.1:20000



# 【日志配置】
Log:
  # 日志冗余度，取值[0,10]
  Verbose: 5
  # 日志记录方式，"console" | "file"
  Way: console
  # 日志记录到目标目录
  Dir: ./logs/



# 【Raft配置】
Raft:
  # Raft开关
  Enable: false

  # Raft结点ID
  ID: NODE-0

  # Bind地址，该地址不能为0.0.0.0
  Bind: 127.0.0.1:17250

  # 集群成员配置json路径
  ClusterConfJson: /home/zwf/zhouwenfeng/GoProj/src/github.com/Hurricanezwf/rate-limiter/conf/raft-cluster.json

  # Raft元数据存储的根目录
  RootDir: ./raft-meta

  # 连接池最大连接数
  TCPMaxPool: 3

  # Raft提交超时时间,单位毫秒
  Timeout: 10000

  # 定时报告谁是Leader的定时器, 单位秒
  LeaderWatchInterval: 60
