// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APIRegistQuotaReq struct {
	RCTypeID             []byte   `protobuf:"bytes,1,opt,name=RCTypeID,proto3" json:"RCTypeID,omitempty"`
	Quota                uint32   `protobuf:"varint,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRegistQuotaReq) Reset()         { *m = APIRegistQuotaReq{} }
func (m *APIRegistQuotaReq) String() string { return proto.CompactTextString(m) }
func (*APIRegistQuotaReq) ProtoMessage()    {}
func (*APIRegistQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e07ba2d713f408f1, []int{0}
}
func (m *APIRegistQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRegistQuotaReq.Unmarshal(m, b)
}
func (m *APIRegistQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRegistQuotaReq.Marshal(b, m, deterministic)
}
func (dst *APIRegistQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRegistQuotaReq.Merge(dst, src)
}
func (m *APIRegistQuotaReq) XXX_Size() int {
	return xxx_messageInfo_APIRegistQuotaReq.Size(m)
}
func (m *APIRegistQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRegistQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIRegistQuotaReq proto.InternalMessageInfo

func (m *APIRegistQuotaReq) GetRCTypeID() []byte {
	if m != nil {
		return m.RCTypeID
	}
	return nil
}

func (m *APIRegistQuotaReq) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

type APIRegistQuotaResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRegistQuotaResp) Reset()         { *m = APIRegistQuotaResp{} }
func (m *APIRegistQuotaResp) String() string { return proto.CompactTextString(m) }
func (*APIRegistQuotaResp) ProtoMessage()    {}
func (*APIRegistQuotaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_e07ba2d713f408f1, []int{1}
}
func (m *APIRegistQuotaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRegistQuotaResp.Unmarshal(m, b)
}
func (m *APIRegistQuotaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRegistQuotaResp.Marshal(b, m, deterministic)
}
func (dst *APIRegistQuotaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRegistQuotaResp.Merge(dst, src)
}
func (m *APIRegistQuotaResp) XXX_Size() int {
	return xxx_messageInfo_APIRegistQuotaResp.Size(m)
}
func (m *APIRegistQuotaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRegistQuotaResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIRegistQuotaResp proto.InternalMessageInfo

func (m *APIRegistQuotaResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIRegistQuotaResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*APIRegistQuotaReq)(nil), "proto.APIRegistQuotaReq")
	proto.RegisterType((*APIRegistQuotaResp)(nil), "proto.APIRegistQuotaResp")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_e07ba2d713f408f1) }

var fileDescriptor_api_e07ba2d713f408f1 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xae, 0x5c, 0x82, 0x8e, 0x01, 0x9e,
	0x41, 0xa9, 0xe9, 0x99, 0xc5, 0x25, 0x81, 0xa5, 0xf9, 0x25, 0x89, 0x41, 0xa9, 0x85, 0x42, 0x52,
	0x5c, 0x1c, 0x41, 0xce, 0x21, 0x95, 0x05, 0xa9, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c,
	0x41, 0x70, 0xbe, 0x90, 0x08, 0x17, 0x2b, 0x58, 0x9d, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6f, 0x10,
	0x84, 0xa3, 0x64, 0xc5, 0x25, 0x84, 0x6e, 0x4c, 0x71, 0x81, 0x90, 0x10, 0x17, 0x8b, 0x73, 0x7e,
	0x4a, 0x2a, 0xd8, 0x0c, 0xde, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0xd9, 0xb7, 0x38, 0x1d, 0xac,
	0x9b, 0x33, 0x08, 0xc4, 0x4c, 0x62, 0x03, 0xbb, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x96,
	0x0a, 0x90, 0x7a, 0x9d, 0x00, 0x00, 0x00,
}
