// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type APIRegistQuotaReq struct {
	RCType               []byte   `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	Quota                uint32   `protobuf:"varint,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRegistQuotaReq) Reset()         { *m = APIRegistQuotaReq{} }
func (m *APIRegistQuotaReq) String() string { return proto.CompactTextString(m) }
func (*APIRegistQuotaReq) ProtoMessage()    {}
func (*APIRegistQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{0}
}
func (m *APIRegistQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRegistQuotaReq.Unmarshal(m, b)
}
func (m *APIRegistQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRegistQuotaReq.Marshal(b, m, deterministic)
}
func (dst *APIRegistQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRegistQuotaReq.Merge(dst, src)
}
func (m *APIRegistQuotaReq) XXX_Size() int {
	return xxx_messageInfo_APIRegistQuotaReq.Size(m)
}
func (m *APIRegistQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRegistQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIRegistQuotaReq proto.InternalMessageInfo

func (m *APIRegistQuotaReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *APIRegistQuotaReq) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

type APIRegistQuotaResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRegistQuotaResp) Reset()         { *m = APIRegistQuotaResp{} }
func (m *APIRegistQuotaResp) String() string { return proto.CompactTextString(m) }
func (*APIRegistQuotaResp) ProtoMessage()    {}
func (*APIRegistQuotaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{1}
}
func (m *APIRegistQuotaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRegistQuotaResp.Unmarshal(m, b)
}
func (m *APIRegistQuotaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRegistQuotaResp.Marshal(b, m, deterministic)
}
func (dst *APIRegistQuotaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRegistQuotaResp.Merge(dst, src)
}
func (m *APIRegistQuotaResp) XXX_Size() int {
	return xxx_messageInfo_APIRegistQuotaResp.Size(m)
}
func (m *APIRegistQuotaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRegistQuotaResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIRegistQuotaResp proto.InternalMessageInfo

func (m *APIRegistQuotaResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIRegistQuotaResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type APIBorrowReq struct {
	RCType               []byte   `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	ClientID             []byte   `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Expire               int64    `protobuf:"varint,3,opt,name=Expire,proto3" json:"Expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIBorrowReq) Reset()         { *m = APIBorrowReq{} }
func (m *APIBorrowReq) String() string { return proto.CompactTextString(m) }
func (*APIBorrowReq) ProtoMessage()    {}
func (*APIBorrowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{2}
}
func (m *APIBorrowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIBorrowReq.Unmarshal(m, b)
}
func (m *APIBorrowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIBorrowReq.Marshal(b, m, deterministic)
}
func (dst *APIBorrowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIBorrowReq.Merge(dst, src)
}
func (m *APIBorrowReq) XXX_Size() int {
	return xxx_messageInfo_APIBorrowReq.Size(m)
}
func (m *APIBorrowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIBorrowReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIBorrowReq proto.InternalMessageInfo

func (m *APIBorrowReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *APIBorrowReq) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *APIBorrowReq) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type APIBorrowResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RCID                 string   `protobuf:"bytes,3,opt,name=RCID,proto3" json:"RCID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIBorrowResp) Reset()         { *m = APIBorrowResp{} }
func (m *APIBorrowResp) String() string { return proto.CompactTextString(m) }
func (*APIBorrowResp) ProtoMessage()    {}
func (*APIBorrowResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{3}
}
func (m *APIBorrowResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIBorrowResp.Unmarshal(m, b)
}
func (m *APIBorrowResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIBorrowResp.Marshal(b, m, deterministic)
}
func (dst *APIBorrowResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIBorrowResp.Merge(dst, src)
}
func (m *APIBorrowResp) XXX_Size() int {
	return xxx_messageInfo_APIBorrowResp.Size(m)
}
func (m *APIBorrowResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIBorrowResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIBorrowResp proto.InternalMessageInfo

func (m *APIBorrowResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIBorrowResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *APIBorrowResp) GetRCID() string {
	if m != nil {
		return m.RCID
	}
	return ""
}

type APIReturnReq struct {
	ClientID             []byte   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RCID                 string   `protobuf:"bytes,2,opt,name=RCID,proto3" json:"RCID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnReq) Reset()         { *m = APIReturnReq{} }
func (m *APIReturnReq) String() string { return proto.CompactTextString(m) }
func (*APIReturnReq) ProtoMessage()    {}
func (*APIReturnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{4}
}
func (m *APIReturnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnReq.Unmarshal(m, b)
}
func (m *APIReturnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnReq.Marshal(b, m, deterministic)
}
func (dst *APIReturnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnReq.Merge(dst, src)
}
func (m *APIReturnReq) XXX_Size() int {
	return xxx_messageInfo_APIReturnReq.Size(m)
}
func (m *APIReturnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnReq proto.InternalMessageInfo

func (m *APIReturnReq) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *APIReturnReq) GetRCID() string {
	if m != nil {
		return m.RCID
	}
	return ""
}

type APIReturnResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnResp) Reset()         { *m = APIReturnResp{} }
func (m *APIReturnResp) String() string { return proto.CompactTextString(m) }
func (*APIReturnResp) ProtoMessage()    {}
func (*APIReturnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{5}
}
func (m *APIReturnResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnResp.Unmarshal(m, b)
}
func (m *APIReturnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnResp.Marshal(b, m, deterministic)
}
func (dst *APIReturnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnResp.Merge(dst, src)
}
func (m *APIReturnResp) XXX_Size() int {
	return xxx_messageInfo_APIReturnResp.Size(m)
}
func (m *APIReturnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnResp proto.InternalMessageInfo

func (m *APIReturnResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIReturnResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type APIReturnAllReq struct {
	ClientID             []byte   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RCType               []byte   `protobuf:"bytes,2,opt,name=RCType,proto3" json:"RCType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnAllReq) Reset()         { *m = APIReturnAllReq{} }
func (m *APIReturnAllReq) String() string { return proto.CompactTextString(m) }
func (*APIReturnAllReq) ProtoMessage()    {}
func (*APIReturnAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{6}
}
func (m *APIReturnAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnAllReq.Unmarshal(m, b)
}
func (m *APIReturnAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnAllReq.Marshal(b, m, deterministic)
}
func (dst *APIReturnAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnAllReq.Merge(dst, src)
}
func (m *APIReturnAllReq) XXX_Size() int {
	return xxx_messageInfo_APIReturnAllReq.Size(m)
}
func (m *APIReturnAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnAllReq proto.InternalMessageInfo

func (m *APIReturnAllReq) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *APIReturnAllReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

type APIReturnAllResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnAllResp) Reset()         { *m = APIReturnAllResp{} }
func (m *APIReturnAllResp) String() string { return proto.CompactTextString(m) }
func (*APIReturnAllResp) ProtoMessage()    {}
func (*APIReturnAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{7}
}
func (m *APIReturnAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnAllResp.Unmarshal(m, b)
}
func (m *APIReturnAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnAllResp.Marshal(b, m, deterministic)
}
func (dst *APIReturnAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnAllResp.Merge(dst, src)
}
func (m *APIReturnAllResp) XXX_Size() int {
	return xxx_messageInfo_APIReturnAllResp.Size(m)
}
func (m *APIReturnAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnAllResp proto.InternalMessageInfo

func (m *APIReturnAllResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIReturnAllResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CMDLeaderNotify struct {
	RaftAddr             string   `protobuf:"bytes,1,opt,name=RaftAddr,proto3" json:"RaftAddr,omitempty"`
	HttpAddr             string   `protobuf:"bytes,2,opt,name=HttpAddr,proto3" json:"HttpAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMDLeaderNotify) Reset()         { *m = CMDLeaderNotify{} }
func (m *CMDLeaderNotify) String() string { return proto.CompactTextString(m) }
func (*CMDLeaderNotify) ProtoMessage()    {}
func (*CMDLeaderNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_5b11e78737a7b0ef, []int{8}
}
func (m *CMDLeaderNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMDLeaderNotify.Unmarshal(m, b)
}
func (m *CMDLeaderNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMDLeaderNotify.Marshal(b, m, deterministic)
}
func (dst *CMDLeaderNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMDLeaderNotify.Merge(dst, src)
}
func (m *CMDLeaderNotify) XXX_Size() int {
	return xxx_messageInfo_CMDLeaderNotify.Size(m)
}
func (m *CMDLeaderNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_CMDLeaderNotify.DiscardUnknown(m)
}

var xxx_messageInfo_CMDLeaderNotify proto.InternalMessageInfo

func (m *CMDLeaderNotify) GetRaftAddr() string {
	if m != nil {
		return m.RaftAddr
	}
	return ""
}

func (m *CMDLeaderNotify) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*APIRegistQuotaReq)(nil), "proto.APIRegistQuotaReq")
	proto.RegisterType((*APIRegistQuotaResp)(nil), "proto.APIRegistQuotaResp")
	proto.RegisterType((*APIBorrowReq)(nil), "proto.APIBorrowReq")
	proto.RegisterType((*APIBorrowResp)(nil), "proto.APIBorrowResp")
	proto.RegisterType((*APIReturnReq)(nil), "proto.APIReturnReq")
	proto.RegisterType((*APIReturnResp)(nil), "proto.APIReturnResp")
	proto.RegisterType((*APIReturnAllReq)(nil), "proto.APIReturnAllReq")
	proto.RegisterType((*APIReturnAllResp)(nil), "proto.APIReturnAllResp")
	proto.RegisterType((*CMDLeaderNotify)(nil), "proto.CMDLeaderNotify")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_5b11e78737a7b0ef) }

var fileDescriptor_api_5b11e78737a7b0ef = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xe6, 0x86, 0x7d, 0xac, 0x6c, 0x06, 0x91, 0xe2, 0xa9, 0xe4, 0xd4, 0x93, 0x17,
	0x11, 0xc4, 0x83, 0x50, 0xdb, 0x81, 0x01, 0x27, 0xf3, 0xe1, 0xc9, 0x5b, 0xa5, 0xd9, 0x28, 0x94,
	0x25, 0xa6, 0x19, 0xba, 0xff, 0x5e, 0xf2, 0xba, 0xd5, 0xba, 0x83, 0xf6, 0xd4, 0xf7, 0x91, 0xfc,
	0xbe, 0xfc, 0x78, 0x14, 0xfc, 0x5c, 0x97, 0x57, 0xda, 0x28, 0xab, 0xd8, 0x88, 0x3e, 0x3c, 0x81,
	0xb3, 0x64, 0x29, 0x50, 0xae, 0xcb, 0xda, 0xbe, 0x6c, 0x95, 0xcd, 0x51, 0x7e, 0xb0, 0x0b, 0x18,
	0x63, 0xfa, 0xba, 0xd3, 0x32, 0xf4, 0x22, 0x2f, 0x9e, 0xe0, 0x3e, 0xb1, 0x73, 0x18, 0xd1, 0x9d,
	0x70, 0x10, 0x79, 0x71, 0x80, 0x4d, 0xe0, 0x77, 0xc0, 0x8e, 0x2b, 0x6a, 0xcd, 0x18, 0x9c, 0xa4,
	0xaa, 0x68, 0x1a, 0x02, 0xa4, 0x99, 0xcd, 0x60, 0xb8, 0xa8, 0xd7, 0x44, 0xfb, 0xe8, 0x46, 0xfe,
	0x06, 0x93, 0x64, 0x29, 0x1e, 0x94, 0x31, 0xea, 0xf3, 0xaf, 0x97, 0x2f, 0xe1, 0x34, 0xad, 0x4a,
	0xb9, 0xb1, 0x22, 0x23, 0x7c, 0x82, 0x6d, 0x76, 0xcc, 0xfc, 0x4b, 0x97, 0x46, 0x86, 0xc3, 0xc8,
	0x8b, 0x87, 0xb8, 0x4f, 0x5c, 0x40, 0xd0, 0xe9, 0xee, 0xab, 0xe4, 0x6e, 0x61, 0x2a, 0x32, 0x2a,
	0xf3, 0x91, 0x66, 0x7e, 0x4f, 0x9a, 0x28, 0xed, 0xd6, 0x6c, 0x9c, 0x66, 0x57, 0xc7, 0x3b, 0xd2,
	0x39, 0xf0, 0x83, 0x0e, 0x7f, 0x43, 0x2a, 0x07, 0xbe, 0xf7, 0x76, 0xe6, 0x30, 0x6d, 0xb1, 0xa4,
	0xaa, 0xfe, 0x7b, 0xf9, 0x67, 0x79, 0x83, 0xee, 0xf2, 0xf8, 0x2d, 0xcc, 0x7e, 0xd7, 0xf4, 0x16,
	0x10, 0x30, 0x4d, 0x17, 0xd9, 0x93, 0xcc, 0x0b, 0x69, 0x9e, 0x95, 0x2d, 0x57, 0x3b, 0x27, 0x80,
	0xf9, 0xca, 0x26, 0x45, 0x61, 0x08, 0xf6, 0xb1, 0xcd, 0xee, 0xec, 0xd1, 0x5a, 0x4d, 0x67, 0x4d,
	0x4b, 0x9b, 0xdf, 0xc7, 0xf4, 0xbf, 0x5d, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x54, 0x11, 0xac,
	0x16, 0x83, 0x02, 0x00, 0x00,
}
