// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// APIRegistQuotaReq 注册资源请求格式
type APIRegistQuotaReq struct {
	RCType        []byte `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	Quota         uint32 `protobuf:"varint,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	ResetInterval int64  `protobuf:"varint,3,opt,name=ResetInterval,proto3" json:"ResetInterval,omitempty"`
	// 以下字段仅内部使用
	Timestamp            int64    `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRegistQuotaReq) Reset()         { *m = APIRegistQuotaReq{} }
func (m *APIRegistQuotaReq) String() string { return proto.CompactTextString(m) }
func (*APIRegistQuotaReq) ProtoMessage()    {}
func (*APIRegistQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{0}
}
func (m *APIRegistQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRegistQuotaReq.Unmarshal(m, b)
}
func (m *APIRegistQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRegistQuotaReq.Marshal(b, m, deterministic)
}
func (dst *APIRegistQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRegistQuotaReq.Merge(dst, src)
}
func (m *APIRegistQuotaReq) XXX_Size() int {
	return xxx_messageInfo_APIRegistQuotaReq.Size(m)
}
func (m *APIRegistQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRegistQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIRegistQuotaReq proto.InternalMessageInfo

func (m *APIRegistQuotaReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *APIRegistQuotaReq) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *APIRegistQuotaReq) GetResetInterval() int64 {
	if m != nil {
		return m.ResetInterval
	}
	return 0
}

func (m *APIRegistQuotaReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// APIRegistQuotaResp 注册资源响应格式
type APIRegistQuotaResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIRegistQuotaResp) Reset()         { *m = APIRegistQuotaResp{} }
func (m *APIRegistQuotaResp) String() string { return proto.CompactTextString(m) }
func (*APIRegistQuotaResp) ProtoMessage()    {}
func (*APIRegistQuotaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{1}
}
func (m *APIRegistQuotaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRegistQuotaResp.Unmarshal(m, b)
}
func (m *APIRegistQuotaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRegistQuotaResp.Marshal(b, m, deterministic)
}
func (dst *APIRegistQuotaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRegistQuotaResp.Merge(dst, src)
}
func (m *APIRegistQuotaResp) XXX_Size() int {
	return xxx_messageInfo_APIRegistQuotaResp.Size(m)
}
func (m *APIRegistQuotaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRegistQuotaResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIRegistQuotaResp proto.InternalMessageInfo

func (m *APIRegistQuotaResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIRegistQuotaResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// APIBorrowReq 借用资源请求格式
type APIBorrowReq struct {
	RCType   []byte `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	ClientID []byte `protobuf:"bytes,2,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Expire   int64  `protobuf:"varint,3,opt,name=Expire,proto3" json:"Expire,omitempty"`
	// 以下字段仅内部使用
	Timestamp            int64    `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIBorrowReq) Reset()         { *m = APIBorrowReq{} }
func (m *APIBorrowReq) String() string { return proto.CompactTextString(m) }
func (*APIBorrowReq) ProtoMessage()    {}
func (*APIBorrowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{2}
}
func (m *APIBorrowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIBorrowReq.Unmarshal(m, b)
}
func (m *APIBorrowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIBorrowReq.Marshal(b, m, deterministic)
}
func (dst *APIBorrowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIBorrowReq.Merge(dst, src)
}
func (m *APIBorrowReq) XXX_Size() int {
	return xxx_messageInfo_APIBorrowReq.Size(m)
}
func (m *APIBorrowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIBorrowReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIBorrowReq proto.InternalMessageInfo

func (m *APIBorrowReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *APIBorrowReq) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *APIBorrowReq) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *APIBorrowReq) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// APIBorrowResp 借用资源响应格式
type APIBorrowResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RCID                 string   `protobuf:"bytes,3,opt,name=RCID,proto3" json:"RCID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIBorrowResp) Reset()         { *m = APIBorrowResp{} }
func (m *APIBorrowResp) String() string { return proto.CompactTextString(m) }
func (*APIBorrowResp) ProtoMessage()    {}
func (*APIBorrowResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{3}
}
func (m *APIBorrowResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIBorrowResp.Unmarshal(m, b)
}
func (m *APIBorrowResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIBorrowResp.Marshal(b, m, deterministic)
}
func (dst *APIBorrowResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIBorrowResp.Merge(dst, src)
}
func (m *APIBorrowResp) XXX_Size() int {
	return xxx_messageInfo_APIBorrowResp.Size(m)
}
func (m *APIBorrowResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIBorrowResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIBorrowResp proto.InternalMessageInfo

func (m *APIBorrowResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIBorrowResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *APIBorrowResp) GetRCID() string {
	if m != nil {
		return m.RCID
	}
	return ""
}

// APIReturnReq 客户端归还单个资源请求格式
type APIReturnReq struct {
	ClientID             []byte   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RCID                 string   `protobuf:"bytes,2,opt,name=RCID,proto3" json:"RCID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnReq) Reset()         { *m = APIReturnReq{} }
func (m *APIReturnReq) String() string { return proto.CompactTextString(m) }
func (*APIReturnReq) ProtoMessage()    {}
func (*APIReturnReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{4}
}
func (m *APIReturnReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnReq.Unmarshal(m, b)
}
func (m *APIReturnReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnReq.Marshal(b, m, deterministic)
}
func (dst *APIReturnReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnReq.Merge(dst, src)
}
func (m *APIReturnReq) XXX_Size() int {
	return xxx_messageInfo_APIReturnReq.Size(m)
}
func (m *APIReturnReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnReq proto.InternalMessageInfo

func (m *APIReturnReq) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *APIReturnReq) GetRCID() string {
	if m != nil {
		return m.RCID
	}
	return ""
}

// APIReturnResp 客户端归还单个资源响应格式
type APIReturnResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnResp) Reset()         { *m = APIReturnResp{} }
func (m *APIReturnResp) String() string { return proto.CompactTextString(m) }
func (*APIReturnResp) ProtoMessage()    {}
func (*APIReturnResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{5}
}
func (m *APIReturnResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnResp.Unmarshal(m, b)
}
func (m *APIReturnResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnResp.Marshal(b, m, deterministic)
}
func (dst *APIReturnResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnResp.Merge(dst, src)
}
func (m *APIReturnResp) XXX_Size() int {
	return xxx_messageInfo_APIReturnResp.Size(m)
}
func (m *APIReturnResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnResp proto.InternalMessageInfo

func (m *APIReturnResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIReturnResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// APIReturnAllReq 客户端释放对某资源占用的请求格式
type APIReturnAllReq struct {
	ClientID             []byte   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	RCType               []byte   `protobuf:"bytes,2,opt,name=RCType,proto3" json:"RCType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnAllReq) Reset()         { *m = APIReturnAllReq{} }
func (m *APIReturnAllReq) String() string { return proto.CompactTextString(m) }
func (*APIReturnAllReq) ProtoMessage()    {}
func (*APIReturnAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{6}
}
func (m *APIReturnAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnAllReq.Unmarshal(m, b)
}
func (m *APIReturnAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnAllReq.Marshal(b, m, deterministic)
}
func (dst *APIReturnAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnAllReq.Merge(dst, src)
}
func (m *APIReturnAllReq) XXX_Size() int {
	return xxx_messageInfo_APIReturnAllReq.Size(m)
}
func (m *APIReturnAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnAllReq proto.InternalMessageInfo

func (m *APIReturnAllReq) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *APIReturnAllReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

// APIReturnAllResp 客户端释放对某资源占用的响应格式
type APIReturnAllResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReturnAllResp) Reset()         { *m = APIReturnAllResp{} }
func (m *APIReturnAllResp) String() string { return proto.CompactTextString(m) }
func (*APIReturnAllResp) ProtoMessage()    {}
func (*APIReturnAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{7}
}
func (m *APIReturnAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReturnAllResp.Unmarshal(m, b)
}
func (m *APIReturnAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReturnAllResp.Marshal(b, m, deterministic)
}
func (dst *APIReturnAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReturnAllResp.Merge(dst, src)
}
func (m *APIReturnAllResp) XXX_Size() int {
	return xxx_messageInfo_APIReturnAllResp.Size(m)
}
func (m *APIReturnAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReturnAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIReturnAllResp proto.InternalMessageInfo

func (m *APIReturnAllResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIReturnAllResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// APIResourceListReq 查询资源列表的请求格式
type APIResourceListReq struct {
	RCType               []byte   `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIResourceListReq) Reset()         { *m = APIResourceListReq{} }
func (m *APIResourceListReq) String() string { return proto.CompactTextString(m) }
func (*APIResourceListReq) ProtoMessage()    {}
func (*APIResourceListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{8}
}
func (m *APIResourceListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResourceListReq.Unmarshal(m, b)
}
func (m *APIResourceListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResourceListReq.Marshal(b, m, deterministic)
}
func (dst *APIResourceListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResourceListReq.Merge(dst, src)
}
func (m *APIResourceListReq) XXX_Size() int {
	return xxx_messageInfo_APIResourceListReq.Size(m)
}
func (m *APIResourceListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResourceListReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIResourceListReq proto.InternalMessageInfo

func (m *APIResourceListReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

// APIResourceListResp 查询资源列表的响应格式
type APIResourceListResp struct {
	Code                 uint32               `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string               `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RCList               []*APIResourceDetail `protobuf:"bytes,3,rep,name=RCList,proto3" json:"RCList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *APIResourceListResp) Reset()         { *m = APIResourceListResp{} }
func (m *APIResourceListResp) String() string { return proto.CompactTextString(m) }
func (*APIResourceListResp) ProtoMessage()    {}
func (*APIResourceListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{9}
}
func (m *APIResourceListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResourceListResp.Unmarshal(m, b)
}
func (m *APIResourceListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResourceListResp.Marshal(b, m, deterministic)
}
func (dst *APIResourceListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResourceListResp.Merge(dst, src)
}
func (m *APIResourceListResp) XXX_Size() int {
	return xxx_messageInfo_APIResourceListResp.Size(m)
}
func (m *APIResourceListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResourceListResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIResourceListResp proto.InternalMessageInfo

func (m *APIResourceListResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIResourceListResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *APIResourceListResp) GetRCList() []*APIResourceDetail {
	if m != nil {
		return m.RCList
	}
	return nil
}

// APIResourceDetail 某资源详情信息
type APIResourceDetail struct {
	RCType               []byte   `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	Quota                uint32   `protobuf:"varint,2,opt,name=Quota,proto3" json:"Quota,omitempty"`
	ResetInterval        int64    `protobuf:"varint,3,opt,name=ResetInterval,proto3" json:"ResetInterval,omitempty"`
	CanBorrowCount       uint32   `protobuf:"varint,4,opt,name=CanBorrowCount,proto3" json:"CanBorrowCount,omitempty"`
	RecycledCount        uint32   `protobuf:"varint,5,opt,name=RecycledCount,proto3" json:"RecycledCount,omitempty"`
	UsedCount            uint32   `protobuf:"varint,6,opt,name=UsedCount,proto3" json:"UsedCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIResourceDetail) Reset()         { *m = APIResourceDetail{} }
func (m *APIResourceDetail) String() string { return proto.CompactTextString(m) }
func (*APIResourceDetail) ProtoMessage()    {}
func (*APIResourceDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{10}
}
func (m *APIResourceDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIResourceDetail.Unmarshal(m, b)
}
func (m *APIResourceDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIResourceDetail.Marshal(b, m, deterministic)
}
func (dst *APIResourceDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIResourceDetail.Merge(dst, src)
}
func (m *APIResourceDetail) XXX_Size() int {
	return xxx_messageInfo_APIResourceDetail.Size(m)
}
func (m *APIResourceDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_APIResourceDetail.DiscardUnknown(m)
}

var xxx_messageInfo_APIResourceDetail proto.InternalMessageInfo

func (m *APIResourceDetail) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

func (m *APIResourceDetail) GetQuota() uint32 {
	if m != nil {
		return m.Quota
	}
	return 0
}

func (m *APIResourceDetail) GetResetInterval() int64 {
	if m != nil {
		return m.ResetInterval
	}
	return 0
}

func (m *APIResourceDetail) GetCanBorrowCount() uint32 {
	if m != nil {
		return m.CanBorrowCount
	}
	return 0
}

func (m *APIResourceDetail) GetRecycledCount() uint32 {
	if m != nil {
		return m.RecycledCount
	}
	return 0
}

func (m *APIResourceDetail) GetUsedCount() uint32 {
	if m != nil {
		return m.UsedCount
	}
	return 0
}

// APIDeleteQuotaReq 删除资源配额请求格式
type APIDeleteQuotaReq struct {
	RCType               []byte   `protobuf:"bytes,1,opt,name=RCType,proto3" json:"RCType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIDeleteQuotaReq) Reset()         { *m = APIDeleteQuotaReq{} }
func (m *APIDeleteQuotaReq) String() string { return proto.CompactTextString(m) }
func (*APIDeleteQuotaReq) ProtoMessage()    {}
func (*APIDeleteQuotaReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{11}
}
func (m *APIDeleteQuotaReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIDeleteQuotaReq.Unmarshal(m, b)
}
func (m *APIDeleteQuotaReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIDeleteQuotaReq.Marshal(b, m, deterministic)
}
func (dst *APIDeleteQuotaReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIDeleteQuotaReq.Merge(dst, src)
}
func (m *APIDeleteQuotaReq) XXX_Size() int {
	return xxx_messageInfo_APIDeleteQuotaReq.Size(m)
}
func (m *APIDeleteQuotaReq) XXX_DiscardUnknown() {
	xxx_messageInfo_APIDeleteQuotaReq.DiscardUnknown(m)
}

var xxx_messageInfo_APIDeleteQuotaReq proto.InternalMessageInfo

func (m *APIDeleteQuotaReq) GetRCType() []byte {
	if m != nil {
		return m.RCType
	}
	return nil
}

// APIDeleteQuotaResp 删除资源配额响应格式
type APIDeleteQuotaResp struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIDeleteQuotaResp) Reset()         { *m = APIDeleteQuotaResp{} }
func (m *APIDeleteQuotaResp) String() string { return proto.CompactTextString(m) }
func (*APIDeleteQuotaResp) ProtoMessage()    {}
func (*APIDeleteQuotaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{12}
}
func (m *APIDeleteQuotaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIDeleteQuotaResp.Unmarshal(m, b)
}
func (m *APIDeleteQuotaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIDeleteQuotaResp.Marshal(b, m, deterministic)
}
func (dst *APIDeleteQuotaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIDeleteQuotaResp.Merge(dst, src)
}
func (m *APIDeleteQuotaResp) XXX_Size() int {
	return xxx_messageInfo_APIDeleteQuotaResp.Size(m)
}
func (m *APIDeleteQuotaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_APIDeleteQuotaResp.DiscardUnknown(m)
}

var xxx_messageInfo_APIDeleteQuotaResp proto.InternalMessageInfo

func (m *APIDeleteQuotaResp) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *APIDeleteQuotaResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// CMDLeaderNotify 下发通知所有结点Leader结点的HTTP服务地址的命令
type CMDLeaderNotify struct {
	RaftAddr             string   `protobuf:"bytes,1,opt,name=RaftAddr,proto3" json:"RaftAddr,omitempty"`
	HttpAddr             string   `protobuf:"bytes,2,opt,name=HttpAddr,proto3" json:"HttpAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMDLeaderNotify) Reset()         { *m = CMDLeaderNotify{} }
func (m *CMDLeaderNotify) String() string { return proto.CompactTextString(m) }
func (*CMDLeaderNotify) ProtoMessage()    {}
func (*CMDLeaderNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{13}
}
func (m *CMDLeaderNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMDLeaderNotify.Unmarshal(m, b)
}
func (m *CMDLeaderNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMDLeaderNotify.Marshal(b, m, deterministic)
}
func (dst *CMDLeaderNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMDLeaderNotify.Merge(dst, src)
}
func (m *CMDLeaderNotify) XXX_Size() int {
	return xxx_messageInfo_CMDLeaderNotify.Size(m)
}
func (m *CMDLeaderNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_CMDLeaderNotify.DiscardUnknown(m)
}

var xxx_messageInfo_CMDLeaderNotify proto.InternalMessageInfo

func (m *CMDLeaderNotify) GetRaftAddr() string {
	if m != nil {
		return m.RaftAddr
	}
	return ""
}

func (m *CMDLeaderNotify) GetHttpAddr() string {
	if m != nil {
		return m.HttpAddr
	}
	return ""
}

// CMDRecycle 下发通知所有结点进行资源清理与回收的命令
type CMDRecycle struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMDRecycle) Reset()         { *m = CMDRecycle{} }
func (m *CMDRecycle) String() string { return proto.CompactTextString(m) }
func (*CMDRecycle) ProtoMessage()    {}
func (*CMDRecycle) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_82d554338aff99dd, []int{14}
}
func (m *CMDRecycle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMDRecycle.Unmarshal(m, b)
}
func (m *CMDRecycle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMDRecycle.Marshal(b, m, deterministic)
}
func (dst *CMDRecycle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMDRecycle.Merge(dst, src)
}
func (m *CMDRecycle) XXX_Size() int {
	return xxx_messageInfo_CMDRecycle.Size(m)
}
func (m *CMDRecycle) XXX_DiscardUnknown() {
	xxx_messageInfo_CMDRecycle.DiscardUnknown(m)
}

var xxx_messageInfo_CMDRecycle proto.InternalMessageInfo

func (m *CMDRecycle) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*APIRegistQuotaReq)(nil), "proto.APIRegistQuotaReq")
	proto.RegisterType((*APIRegistQuotaResp)(nil), "proto.APIRegistQuotaResp")
	proto.RegisterType((*APIBorrowReq)(nil), "proto.APIBorrowReq")
	proto.RegisterType((*APIBorrowResp)(nil), "proto.APIBorrowResp")
	proto.RegisterType((*APIReturnReq)(nil), "proto.APIReturnReq")
	proto.RegisterType((*APIReturnResp)(nil), "proto.APIReturnResp")
	proto.RegisterType((*APIReturnAllReq)(nil), "proto.APIReturnAllReq")
	proto.RegisterType((*APIReturnAllResp)(nil), "proto.APIReturnAllResp")
	proto.RegisterType((*APIResourceListReq)(nil), "proto.APIResourceListReq")
	proto.RegisterType((*APIResourceListResp)(nil), "proto.APIResourceListResp")
	proto.RegisterType((*APIResourceDetail)(nil), "proto.APIResourceDetail")
	proto.RegisterType((*APIDeleteQuotaReq)(nil), "proto.APIDeleteQuotaReq")
	proto.RegisterType((*APIDeleteQuotaResp)(nil), "proto.APIDeleteQuotaResp")
	proto.RegisterType((*CMDLeaderNotify)(nil), "proto.CMDLeaderNotify")
	proto.RegisterType((*CMDRecycle)(nil), "proto.CMDRecycle")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_82d554338aff99dd) }

var fileDescriptor_api_82d554338aff99dd = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xef, 0x8a, 0xd3, 0x40,
	0x10, 0x27, 0xcd, 0xb5, 0x98, 0xb1, 0xf1, 0xce, 0x55, 0x24, 0x88, 0x1f, 0xca, 0x22, 0x52, 0x54,
	0x0e, 0x51, 0x04, 0xf1, 0x83, 0x50, 0x93, 0x03, 0x03, 0x57, 0x39, 0x87, 0xf3, 0x01, 0x62, 0x33,
	0x77, 0x04, 0xd2, 0x6c, 0xdc, 0x6c, 0xf5, 0xfa, 0x00, 0x3e, 0xa1, 0x2f, 0x24, 0x3b, 0x49, 0xdb,
	0xa4, 0xc2, 0x35, 0x5f, 0xee, 0xd3, 0xee, 0xcc, 0xfe, 0x7e, 0xb3, 0xbf, 0xf9, 0x07, 0x5e, 0x52,
	0x66, 0xa7, 0xa5, 0x56, 0x46, 0x89, 0x21, 0x1f, 0xf2, 0x8f, 0x03, 0x0f, 0x67, 0x17, 0x31, 0xd2,
	0x75, 0x56, 0x99, 0x6f, 0x2b, 0x65, 0x12, 0xa4, 0x9f, 0xe2, 0x09, 0x8c, 0x30, 0xbc, 0x5c, 0x97,
	0x14, 0x38, 0x13, 0x67, 0x3a, 0xc6, 0xc6, 0x12, 0x8f, 0x61, 0xc8, 0x98, 0x60, 0x30, 0x71, 0xa6,
	0x3e, 0xd6, 0x86, 0x78, 0x0e, 0x3e, 0x52, 0x45, 0x26, 0x2e, 0x0c, 0xe9, 0x5f, 0x49, 0x1e, 0xb8,
	0x13, 0x67, 0xea, 0x62, 0xd7, 0x29, 0x9e, 0x81, 0x77, 0x99, 0x2d, 0xa9, 0x32, 0xc9, 0xb2, 0x0c,
	0x8e, 0x18, 0xb1, 0x73, 0xc8, 0x8f, 0x20, 0xf6, 0x65, 0x54, 0xa5, 0x10, 0x70, 0x14, 0xaa, 0xb4,
	0x56, 0xe1, 0x23, 0xdf, 0xc5, 0x09, 0xb8, 0xf3, 0xea, 0x9a, 0x15, 0x78, 0x68, 0xaf, 0xf2, 0x06,
	0xc6, 0xb3, 0x8b, 0xf8, 0xb3, 0xd2, 0x5a, 0xfd, 0xbe, 0x4d, 0xfd, 0x53, 0xb8, 0x17, 0xe6, 0x19,
	0x15, 0x26, 0x8e, 0x98, 0x3e, 0xc6, 0xad, 0x6d, 0x39, 0x67, 0x37, 0x65, 0xa6, 0xa9, 0x11, 0xdf,
	0x58, 0x07, 0x54, 0xc7, 0xe0, 0xb7, 0x7e, 0xee, 0x2b, 0xd8, 0xa2, 0x30, 0x8c, 0x23, 0xfe, 0xca,
	0x43, 0xbe, 0xcb, 0x4f, 0x9c, 0x04, 0x92, 0x59, 0xe9, 0xc2, 0x26, 0xd1, 0x16, 0xeb, 0xec, 0x89,
	0xdd, 0xf0, 0x07, 0x2d, 0xfe, 0x7b, 0x96, 0xb2, 0xe1, 0xf7, 0xae, 0xdd, 0x19, 0x1c, 0x6f, 0x69,
	0xb3, 0x3c, 0x3f, 0xf4, 0xf3, 0xae, 0xb4, 0x83, 0x76, 0x69, 0xe5, 0x07, 0x38, 0xe9, 0x86, 0xe9,
	0x2d, 0xe0, 0x75, 0xd3, 0xf8, 0x4a, 0xad, 0xf4, 0x82, 0xce, 0xb3, 0xca, 0xdc, 0xd2, 0x42, 0xb9,
	0x84, 0x47, 0xff, 0xa1, 0x7b, 0x97, 0xfd, 0x8d, 0x0d, 0x6a, 0x39, 0x81, 0x3b, 0x71, 0xa7, 0xf7,
	0xdf, 0x06, 0xf5, 0x2a, 0x9c, 0xb6, 0x22, 0x46, 0x64, 0x92, 0x2c, 0xc7, 0x06, 0x27, 0xff, 0x6e,
	0xb6, 0xa3, 0xfd, 0x7a, 0x27, 0xdb, 0xf1, 0x02, 0x1e, 0x84, 0x49, 0x51, 0x4f, 0x52, 0xa8, 0x56,
	0x85, 0xe1, 0x61, 0xf3, 0x71, 0xcf, 0x5b, 0x47, 0x5b, 0xac, 0x17, 0x39, 0xa5, 0x35, 0x6c, 0xc8,
	0xb0, 0xae, 0xd3, 0x4e, 0xed, 0xf7, 0x6a, 0x83, 0x18, 0x31, 0x62, 0xe7, 0x90, 0xaf, 0x38, 0xa9,
	0x88, 0x72, 0x32, 0x74, 0x68, 0xe5, 0x9b, 0xc5, 0xec, 0x80, 0x7b, 0xf7, 0x36, 0x86, 0xe3, 0x70,
	0x1e, 0x9d, 0x53, 0x92, 0x92, 0xfe, 0xaa, 0x4c, 0x76, 0xb5, 0xb6, 0xc3, 0x85, 0xc9, 0x95, 0x99,
	0xa5, 0xa9, 0x66, 0xb2, 0x87, 0x5b, 0xdb, 0xbe, 0x7d, 0x31, 0xa6, 0xe4, 0xb7, 0x3a, 0xca, 0xd6,
	0x96, 0x2f, 0x01, 0xc2, 0x79, 0xd4, 0x64, 0xd9, 0xdd, 0x4a, 0x67, 0x6f, 0x2b, 0x7f, 0x8c, 0xb8,
	0xad, 0xef, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x20, 0x11, 0xf1, 0x12, 0xee, 0x04, 0x00, 0x00,
}
